# TEMP CHANGE TO THIS FILE (need to move to corret folder in metrics java sample app)
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  prometheusremotewrite: 
    endpoint: "http://localhost:9411/api/prom/push"
    insecure: true # temporarily to avoid setting cert_file and key_file

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      exporters: [logging]
    metrics/2:
      receivers: [otlp]
      exporters: [prometheusremotewrite]
